<style type="text/css">
      <!--
        body {
        background-image: url(image/IndexBg_6.jpg);
        background-repeat:repeat;
       /* background-position:bottom;*/
        background-attachment:fixed;
        }
      -->
</style>
<body>
<p>this is controll panel</p>

<a href='/manage/addavui'>add av</a>
<a href='/manage/deleteavui'>delete av</a>
<a href='/manage/cleanbarrageui'>clean barrage</a>
<p> other manage method</p>
</body>