<html>
<head>
<link rel="shortcut icon" href="image/icon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/css/style.css" />
<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style type="text/css">
<!--
body {
	/*background-image: url(image/IndexBg_6.jpg);*/
	background-repeat: repeat;
	/* background-position:bottom;*/
	background-attachment: fixed;
}

-->
body,div {
	margin: 0;
	padding: 0
	 text-align:center;
	 margin:0px auto; 
}

img {
	border: 0
}

#container {
	text-align: center
}

#container .cell {
	padding: 5px 5px 0;
	border: 1px solid #E3E3E3;
	background: #F5F5F5;
	margin-top: 10px
	
}

#container p {
	line-height: 20px;
	margin-top: 5px
 	font-size:2px;
}

</style>


<script type="text/javascript" src="/js/jquery.waterfall.js"></script>

</head>
<body>

	<div id="container" align="center"></div>

	<div id="waterfall"></div>
	<script type="text/javascript">
	$(function(){
		// 一次性全部加载到本地，再部分显示
		$('#waterfall').waterfall({
			url: '/index/waterfall',
			perNum: 5,			// 每次显示五个
			ajaxTimes: 1 		// 只发送一次请求
		});
		
		

	});
</script>
</body>