
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title> 404 error: Page not found</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<style type="text/css">
.STYLE1 {
    color:#0000FF; 
    font-weight:bold; 
    font-size:25px
    font-weight: bold;
}
 
.STYLE2{
    font-size:15px;
    line-height:25px
}
</style>
</head>
<body style="margin-top:100px;">
    <div style="margin:0 auto; width:650px;">
        <p>
            <h3 class="STYLE1">很抱歉，您要访问的页面不存在。</h3>
            <h3 class="STYLE1">
                Sorry, the page you are trying to access
                does not exist or perhaps it was removed.
            </h3>
        </p>
 
        <br />
 
        <p>
            <h2 class="STYLE2">
                1、请检查您输入的地址是否正确。(Please check your input)
            </h2>
        </p>
 
        <p>
            <h2 class="STYLE2">
                2、通过 <a href="/index">首页</a> 进行浏览。
                (Welcome back to home page
           
        </p>
 
        <p>
            <h2 class="STYLE2">
                3、感谢您使用本站，如有疑问请<a href="xxxxxxxx">联系我</a>。
                (Thank you for visiting and
                <a href="xxxxxxxxxxxx">contract me</a> if any question)
            </h2>
        </p>
	        <p>
            <h2 class="STYLE2">
         
                powered by JINET
            </h2>
        </p>
    </div>
</body>
</html>